#include "Maze.h"
#include "Solver.h"
#include "DFS.h"
#include "BFS.h"
#include "MazeGenerator.h"

#include <iostream>
#include <vector>
#include <string>

int main() {
    MazeGenerator MG(15,15);
    Maze generatedMaze = MG.generate();
    std::cout << "Maze generated by MazeGenerator: \n";
    generatedMaze.printWithoutSolution();

    BFS bfs1(generatedMaze);
    bool foundBFS1 = bfs1.bfs();
    if (foundBFS1) {
        std::cout << "Solution found with BFS: \n";
        generatedMaze.printWithSolution(bfs1.solution());
    } else {
        std::cout << "Solution not found\n";
    }

    std::vector<std::string> externalMazeString = {
        "#####################",
        "#S....#.......#.....#",
        "#.#.#.#.#####.#.###.#",
        "#...#.#.....#.#...#.#",
        "#.###.#####.#.###.#.#",
        "#.#...#...#.#...#.#.#",
        "#.#.###.#.#.###.#.#.#",
        "#.#.....#.#.....#...#",
        "#.#######.#######.###",
        "#.....#...#.....#...#",
        "###.#.#.###.###.#.#.#",
        "#...#.....#...#.#.#.#",
        "#.###.###.###.#.#.#.#",
        "#.#.....#.....#.#...#",
        "#.#.###.#######.###.#",
        "#...#...#.....#...#.#",
        "###.###.#.###.#.###.#",
        "#.....#.#.#...#.....#",
        "#.#####.#.#.#######.#",
        "#.......#...#......E#",
        "#####################"
    };
    std::cout << "External maze: \n";
    Maze externalMaze(externalMazeString);
    externalMaze.printWithoutSolution();

    BFS bfs2(externalMaze);
    bool foundBFS2 = bfs2.bfs();
    if (foundBFS2) {
        std::cout << "Solution found with BFS: \n";
        externalMaze.printWithSolution(bfs2.solution());
    } else {
        std::cout << "Solution not found\n";
    }

    DFS dfs2(externalMaze);
    bool foundDFS2 = dfs2.dfs();
    if (foundDFS2) {
        std::cout << "Solution found with DFS: \n";
        externalMaze.printWithSolution(dfs2.solution());
    } else {
        std::cout << "Solution not found\n";
    }


    return 0;
}
